15-410 Project 0: traceback.h File Reference
traceback.h File Reference
Function prototype(s) for traceback library.
#include <stdio.h>
Functions
void traceback (FILE *)
Print the chain of function calls in reverse order.
void * getFirstStack ()
Get the last function call's ebp address, excluding the traceback itself.
int funcs_find (void *addr)
Find a specified function in the global function symbol table. If found, return the index to the function in the symbol table, return -1 otherwise.
Detailed Description
Function prototype(s) for traceback library.
DO NOT EDIT THIS FILE
Author
Michael Ashley-Rollman(mpa)
Function Documentation
int funcs_find (void * addr)
Find a specified function in the global function symbol table. If found, return the index to the function in the symbol table, return -1 otherwise.
Parameters
addr The specified address of the wanted function.
Returns
The index to the function in the symbol table if found, return -1 otherwise.
Referenced by traceback().
void* getFirstStack ()
Get the last function call's ebp address, excluding the traceback itself.
Returns
The last function call's ebp address.
Referenced by traceback().
void traceback (FILE *)
Print the chain of function calls in reverse order.
Parameters
fp Specifies where to output the trace information.
References funcs_find(), and getFirstStack().