15-410 Project 0: traceback.c File Reference
traceback.c File Reference
The traceback function.
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "contracts.h"
#include "traceback_internal.h"
Functions
int funcs_find (int addr)
Find a specified function in the global function symbol table. If found, return the index to the function in the symbol table, return -1 otherwise.
void print_func (FILE *fp, int ebp, int func_index)
Print the specified functions argument.
void print_main (FILE *fp, int ebp, int func_index)
Print main.
void traceback (FILE *fp)
Print the chain of function calls in reverse order.
Detailed Description
The traceback function.
This file contains the traceback function for the traceback library
2016-01-04 Mon 07:37 PM
Author
Harry Q. Bovik (hqbovik)
Bug:
Could not pass the signal handling test case.
Function Documentation
int funcs_find (int addr)
Find a specified function in the global function symbol table. If found, return the index to the function in the symbol table, return -1 otherwise.
Parameters
addr The specified address of the wanted function.
Returns
The index to the function in the symbol table if found, return -1 otherwise.
Referenced by traceback().
void print_func (FILE * fp, int ebp, int func_index)
Print the specified functions argument.
Parameters
fp Specifies where to output the function information.
ebp The specified function's stack base register.
func_index The specified function's index in the global functions table.
Referenced by traceback().
void print_main (FILE * fp, int ebp, int func_index)
Print main.
Parameters
fp Specifies where to output the function information.
ebp main's stack base register.
func_index main's index in the global functions table.
Referenced by traceback().
void traceback (FILE *)
Print the chain of function calls in reverse order.
Parameters
fp Specifies where to output the trace information.
References funcs_find(), getFirstStack(), print_func(), and print_main().